userId: 5000

users:
  - name: Luke
  - name: !ref ./config.test.json#userId

api2Url: !ref env:BASE_URL#$ & '/v2'
api3Url: !ref "#userId"

api4Url: !query "$replace($ref('env:BASE_URL'), 'http:', 'https:') & '/v4'"

apiId: !ref
  uri: https://random-data-api.com/api/beer/random_beer#id
  opts:
    watchInterval: 1000

password: !ref ./password

logo: !ref logo_w200.jpeg